label test:
    play sound "audio/soundFX/FX4/bonk.wav"
    "bonk"
    play sound "audio/soundFX/FX4/clothing2.wav"
    "cloth2"
    play sound "audio/soundFX/FX4/clothing2b.wav"
    "cloth2b"
    play sound "audio/soundFX/FX4/clothing3.wav"
    "cloth3"
    play sound "audio/soundFX/FX4/clothrip.wav"
    "clothrip"
    play sound "audio/soundFX/FX4/fwunk.wav"
    "fwunk"
    play sound "audio/soundFX/FX4/lightclunk.wav"
    "lightclunk"
    play sound "audio/soundFX/FX4/metalimpact.wav"
    "metalimpact"
    play sound "audio/soundFX/FX4/mugwood.wav"
    "mugwood"
    play sound "audio/soundFX/FX4/potscans39.wav"
    "potcans39"
    play sound "audio/soundFX/FX4/rip1.wav"
    "rip1"
    play sound "audio/soundFX/FX4/stairs1.wav"
    "stairs1"
    play sound "audio/soundFX/FX4/stairs2.wav"
    "stairs2"
    play sound "audio/soundFX/FX4/stroke1.wav"
    "stroke1"
    play sound "audio/soundFX/FX4/stroke2.wav"
    "stroke2"
    play sound "audio/soundFX/FX4/stroke3.wav"
    "stroke3"
    play sound "audio/soundFX/FX4/stroke4.wav"
    "stroke4"
    play sound "audio/soundFX/FX4/tearing fabric.wav"
    "tearingfabric"
    play sound "audio/soundFX/FX4/waterpaddle.wav"
    "waterpaddle"
    jump test
    return
